# -*- coding: utf-8 -*-
"""Heart Disease - Text and Web Analytics - Spring 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCMQeFWo0QBrWHVIwMz2n3hH6RPs5n5e
"""

#install packages prior to uploading dataset
install.packages("ggplot2")
install.packages("caret")
install.packages("rpart")
install.packages("randomForest")
install.packages("class")

#Load libraries through installed packages
library(ggplot2)
library(caret)
library(rpart)
library(randomForest)
library(class)

#Load dataset and intialize variable for it
heart_data <- read.csv("heart.csv")

#First 6 records in the dataset
head(heart_data)

#Last 6 records in the dataset
tail(heart_data)

#Number of dimensions in the dataset (row x column)
dim(heart_data)

#Name of each feature in the dataset
colnames(heart_data)

#Structure of the dataset
str(heart_data)

#Statistical information about the dataset
summary(heart_data)

#Check which columns have missing data and how much missing data in total
colSums(is.na(heart_data))

sum(is.na(heart_data))

#Check if there any duplicate records and how many such records
sum(duplicated(heart_data))

heart_data[duplicated(heart_data), ]

#Remove duplicate record
heart_data <- unique(heart_data)

#Check number of records in each target variable clas
table(heart_data$target)

#Display the above distribution in percentage
prop.table(table(heart_data$target))*100

#Boxplot for Age
boxplot(heart_data$age,
        main = "Boxplot of Age")

#Boxplot for cholesterol
boxplot(heart_data$chol,
        main = "Boxplot of Cholesterol")

#Boxplot of Resting Blood Pressure
boxplot(heart_data$trestbps,
        main = "Boxplot of Resting Blood Pressure")

#Initialize a variable to hold the rescaled values of all records for all features in the dataset
heart_scaled <- heart_data

heart_scaled[,1:13] <- scale(heart_scaled[,1:13])

head(heart_scaled)

#Divide dataset into training and testing sets
set.seed(123)

trainIndex <- createDataPartition(
  heart_data$target,
  p = 0.7,
  list = FALSE
)

train_data <- heart_data[trainIndex, ]
test_data <- heart_data[-trainIndex, ]

#Dimensions of the training and testing sets
dim(train_data)
dim(test_data)

#View the training and testing dataset
table(train_data$target)

table(test_data$target)

#Mean Analysis
mean(heart_data$age)

mean(heart_data$chol)

mean(heart_data$trestbps)