# -*- coding: utf-8 -*-
"""X-Ray Fracture Detection - Spring 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Js0FOHU--eoxXqaj8ghi6ojzUKPNTcDg
"""

#import libraries
import os
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Flatten,
    Dense,
    Dropout,
    BatchNormalization
)
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.applications import MobileNetV2

from sklearn.metrics import classification_report, confusion_matrix

#import dataset from Kaggle directly
import kagglehub

# Download latest version
path = kagglehub.dataset_download("devbatrax/fracture-detection-using-x-ray-images")

print("Path to dataset files:", path)

#check where dataset is located
print(path)

#what folder is inside download
os.listdir(path)

#how data has been structured inside the 'data' folder
for root, dirs, files in os.walk(path):
    print("ROOT:", root)
    print("DIRS:", dirs)
    print("FILES:", len(files))
    print("-" * 50)

#root directory is hidden by default, we copy dataset to 'content' folder to see the contents of it
import shutil
shutil.copytree(path, "/content/fracture_dataset")

dataset_path = "/content/fracture_dataset"

#set training and validation paths
train_dir = path + "/data/train"
val_dir = path + "/data/val"

#Change image attributes to produce images of the same subjects but altered for training dataset
#This will allow better generalization of model
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    zoom_range=0.1,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest'
)

#Normalize validation dataset (no alteration since we predict on this dataset)
val_datagen = ImageDataGenerator(
    rescale=1./255
)

#Training dataset setup
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(128, 128),
    batch_size=32,
    class_mode='binary',
    shuffle=True
)

#Validation dataset setup
val_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=(128, 128),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)

#check if labels are correct('0' for no and '1' for yes)
print(train_generator.class_indices)

#CNN Model
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
    MaxPooling2D(2,2),
    BatchNormalization(),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    BatchNormalization(),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    BatchNormalization(),

    Flatten(),

    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

#Measuring loss and optimizing according to it
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#View model
model.summary()

#Training CNN Model
history = model.fit(train_generator, validation_data=val_generator, epochs = 15)

#Reduce Epochs and introduce callbacks to see if Accuracy improves(reduce overfitting)
history = model.fit(train_generator,
                    validation_data=val_generator,
                    epochs = 10,
                    callbacks=[tf.keras.callbacks.EarlyStopping(
                        monitor='val_loss',
                        patience=3,
                        restore_best_weights=True)])

#Accuracy Graph
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.title('Training vs Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

#Loss Graph
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.title('Training vs Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

#Classification Report
predictions = model.predict(val_generator)
predicted_classes = (predictions > 0.5).astype(int)
true_classes = val_generator.classes

print(classification_report(true_classes, predicted_classes))

#Confusion Matrix with Heatmap
cm = confusion_matrix(true_classes, predicted_classes)
plt.figure(figsize=(6, 4))
plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.colorbar()
plt.xticks([0, 1], ['Fractured', 'Not Fractured'])
plt.yticks([0, 1], ['Fractured', 'Not Fractured'])
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')

for i in range(2):
  for j in range(2):
    plt.text(j, i, cm[i, j], ha='center', va='center', color='black')

plt.show()

#Using pre-trained model MobileNetV2 now

#Normalize dataset for pre-trained model
train_datagen_mobilenet = ImageDataGenerator(
    preprocessing_function=preprocess_input)
val_datagen_mobilenet = ImageDataGenerator(
    preprocessing_function=preprocess_input)

#Pre-trained models' training dataset setup
train_generator_mobilenet = train_datagen_mobilenet.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=True
)

#Pre-trained models' validation dataset setup
val_generator_mobilenet = val_datagen_mobilenet.flow_from_directory(
    val_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)

#Load pre-trained model
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False

#Transfer Learning through CNN Model
model_mobilenet = Sequential([
    base_model,
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

#Compilation and Loss Optimizer
model_mobilenet.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#View pre-trained model
model_mobilenet.summary()

#Train pre-trained model with the given dataset
history_mobilenet = model_mobilenet.fit(train_generator_mobilenet,
                                        validation_data=val_generator_mobilenet,
                                        epochs = 10,
                                        callbacks=[tf.keras.callbacks.EarlyStopping(
                                            monitor='val_loss',
                                            patience=3,
                                            restore_best_weights=True)
                                        ])

#Accuracy Graph for Pre-trained model
plt.plot(history_mobilenet.history['accuracy'], label='Training Accuracy')
plt.plot(history_mobilenet.history['val_accuracy'], label='Validation Accuracy')

plt.title('Training vs Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

#Loss Graph for Pre-trained model
plt.plot(history_mobilenet.history['loss'], label='Training Loss')
plt.plot(history_mobilenet.history['val_loss'], label='Validation Loss')

plt.title('Training vs Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

#Classification Report
predictions_mobilenet = model_mobilenet.predict(val_generator_mobilenet)
predicted_classes_mobilenet = (predictions_mobilenet > 0.5).astype(int).flatten()
true_classes_mobilenet = val_generator_mobilenet.classes

print(classification_report(true_classes_mobilenet, predicted_classes_mobilenet))

#Confusion Matrix with Heatmap for Pre-trained model
cm = confusion_matrix(true_classes_mobilenet, predicted_classes_mobilenet)
plt.figure(figsize=(6, 4))
plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Reds)
plt.title('Confusion Matrix')
plt.colorbar()
plt.xticks([0, 1], ['Fractured', 'Not Fractured'])
plt.yticks([0, 1], ['Fractured', 'Not Fractured'])
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')

for i in range(2):
  for j in range(2):
    plt.text(j, i, cm[i, j], ha='center', va='center', color='black')

plt.show()